from setuptools import setup, find_packages
import os
import subprocess

# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'version.py')

try:
    version_git = subprocess.check_output(["git", "describe"]).rstrip()
except:
    with open(version_py, 'r') as fh:
        version_git = fh.read().decode('utf-8').strip().split('=')[-1].replace('"','')

version_msg = b"""
# Do not edit this file.

# To bump the version run:
# git -a tag vx.x.x -m "Tag Message"
# python setup.py install
# NB - to push a tag to github you have to run
# git push origin vx.x.x
"""
with open(version_py, 'w') as fh:
    message = version_msg + os.linesep.encode('utf-8') + b"__version__=" + version_git
    fh.write(message.decode('utf-8'))

setup(name='terrapin',
      version="{ver}".format(ver=version_git),
      packages=find_packages()
)
